-- drop_all.sql
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS booking_times CASCADE;
DROP TABLE IF EXISTS user_state CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS specialist_services CASCADE;
DROP TABLE IF EXISTS services CASCADE;
DROP TABLE IF EXISTS specialists CASCADE;
